DROP TABLE USERS;
DROP TABLE DEPARTMENT;
DROP TABLE BOOKS;
DROP TABLE BIDDING_DETAILS;
DROP TABLE BANKING_DETAILS;
DROP TABLE NOTIFICATION;
DROP TABLE FINALBIDDING;
DROP TABLE PAYMENT;

DROP TABLE RATESERVICE;
